version: '3'
services:
  # nginx:
  #   build: ./nginx
  #   links:
  #     - app1:app1
  #     - app2:app2
  #   ports:
  #     - "80:80"

  app1:
    container_name: chatter1
    build: .
    ports:
      - 3000:3000
    environment:
      WAIT_HOSTS: postgres:5432
      NODE_ENV: production
    depends_on:
      - postgres
    links:
      - postgres

  # app2:
  #   container_name: chatter2
  #   build: .
  #   ports:
  #     - 3001:3000
  #   environment:
  #     POSTGRES_HOST: twitter:twitter@postgres:5432
  #     PORT: 3000

  #   depends_on:
  #     - postgres
  #     - redis
  #   links:
  #     - postgres

  # redis:
  #   image: redis:6.2.4
  
  postgres:
    container_name: postgres
    restart: always
    image: "postgres:13-alpine"
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
volumes: 
  pg_data:
    driver: local